  steps:
    - label: Bon 9
#      plugins:
#        - docker#v5.12.0:
#            image: "huggingface/transformers-torch-light"
#            always-pull: true
      commands:
        - "echo 9"
        - "pwd"
        - "echo $(python3 --version)"
        - "echo $$BUILDKITE_RETRY_COUNT"
        - "echo $$BUILDKITE_BRANCH"
        - 'if [ "$$BUILDKITE_RETRY_COUNT" = "1" ]; then exit 0; else exit 1; fi'
      parallelism: 2

    - label: Mal 10
      plugins:
        - docker#v5.12.0:
            image: "huggingface/transformers-torch-light"
            always-pull: true
            propagate-environment: true
      commands:
        - "pwd"
        - "echo 3"
        - "ls -la /workdir"
        - "pip install -e ."
        - "echo $$BUILDKITE_RETRY_COUNT"
        - "echo $$BUILDKITE_BRANCH"
        - 'if [ "$$BUILDKITE_RETRY_COUNT" = "1" ]; then exit 0; else exit 1; fi'
##        - "python3 -m pytest -v tests/models/vit/test_modeling_vit.py::ViTModelTest::test_config"
#        - "python3 -m pytest -v tests/models/vit/test_modeling_vit.py -k ViTModelTest"
      parallelism: 2

    - label: OK 11
      plugins:
        - docker#v5.12.0:
            image: "huggingface/transformers-torch-light"
            always-pull: true
      commands:
        - "pwd"
        - "echo 4"
        - "ls -la /workdir"
        - "pip install -e ."
#        - "python3 -m pytest -v tests/models/vit/test_modeling_vit.py::ViTModelTest::test_config"
        - "echo $$BUILDKITE_RETRY_COUNT"
        - "echo $$BUILDKITE_BRANCH"
        #        - "python3 -m pytest -v tests/models/vit/test_modeling_vit.py -k ViTModelTest"
#        - 'if [ "$$BUILDKITE_RETRY_COUNT" = "1" ]; then exit 0; else exit 1; fi'
      parallelism: 2