name: Build PR Documentation

on:
  pull_request:
  workflow_call:
    inputs:
      pr_number:
        type: string
        required: true
      commit_sha:
        type: string
        required: true


concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    uses: huggingface/doc-builder/.github/workflows/build_pr_documentation.yml@6e2eb04a2604817c97be03786efa494fe3acae90
    with:
      commit_sha: ${{ inputs.commit_sha || github.event.pull_request.head.sha }}
      pr_number: ${{ inputs.pr_number || github.event.number }}
      package: transformers
      languages: en
      repo_owner: ydshieh
