name: Self-hosted runner (AMD mi210 scheduled CI caller)

on:
  workflow_run:
    workflows: ["Self-hosted runner (AMD scheduled CI caller)"]
    branches: ["all_jobs_can_compare_against_prev_runs_clean_trigger"]
    types: [completed]
  push:
    branches:
      - run_amd_scheduled_ci_caller*

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-22.04
    steps:
      - name: Update clone

        run: |
          echo ${{ github.event_name }}
          echo ${{ github.event.workflow_run.head_branch }}
          echo ${{ github.event.workflow_run.event }}
          echo $GITHUB_EVENT_NAME
          echo $GITHUB_EVENT_PATH
          cat $GITHUB_EVENT_PATH
          echo ${{ toJson(github.event.workflow_run) }}
