name: Self-hosted runner (scheduled)

# Note that each job's dependencies go into a corresponding docker file.
#
# For example for `run_torch_cuda_extensions_gpu` the docker image is
# `huggingface/transformers-pytorch-deepspeed-latest-gpu`, which can be found at
# `docker/transformers-pytorch-deepspeed-latest-gpu/Dockerfile`

on:
  workflow_call:
    inputs:
      job:
        required: true
        type: string
      slack_report_channel:
        required: true
        type: string
      runner:
        required: true
        type: string
      docker:
        required: true
        type: string
      ci_event:
        required: true
        type: string
      working-directory-prefix:
        default: ''
        required: false
        type: string

env:
  HF_HOME: /mnt/cache
  TRANSFORMERS_IS_CI: yes
  OMP_NUM_THREADS: 8
  MKL_NUM_THREADS: 8
  RUN_SLOW: yes
  # For gated repositories, we still need to agree to share information on the Hub repo. page in order to get access.
  # This token is created under the bot `hf-transformers-bot`.
  HF_HUB_READ_TOKEN: ${{ secrets.HF_HUB_READ_TOKEN }}
  SIGOPT_API_TOKEN: ${{ secrets.SIGOPT_API_TOKEN }}
  TF_FORCE_GPU_ALLOW_GROWTH: true
  CUDA_VISIBLE_DEVICES: 0,1
  NUM_SLICES: 2

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-22.04
    steps:
      - name: Update clone
        run: |
          echo ${{ github.event.inputs.prev_workflow_run_id || 'ydshieh' }}
          echo ${{ github.event.inputs.other_workflow_run_id || 'ydshieh 2' }}
          echo ${{ github.event.inputs.ci_event || 'ydshieh 3' }}
          echo ${{ inputs.prev_workflow_run_id || 'ydshieh 4' }}
          echo ${{ inputs.other_workflow_run_id || 'ydshieh 5' }}
          echo ${{ inputs.ci_event  || 'ydshieh 6' }}


  setup2:
    name: Setup3
    runs-on: ubuntu-22.04
    steps:
      - name: Wait
        run: |
          sleep 10
      
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
            pattern: values*
            path: values
      
      - name: Check
        run: |
          ls -la
          ls -la values
          cat values/prev_workflow_run_id.txt
          cat values/other_workflow_run_id.txt
