name: Self-hosted runner (nightly-ci)


on:
  repository_dispatch:
  # triggered when the daily scheduled Nvidia CI is completed.
  # This way, we can compare the results more easily.
  workflow_run:
    workflows: ["Self-hosted runner (scheduled)"]
    branches: ["main"]
    types: [completed]
  push:
    branches:
      - fix_nightly_ci

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-22.04
    steps:
      - name: Setup
        run: |
          echo "Hello 2"
