name: Self-hosted runner (AMD scheduled CI caller)

on:
  push:
    branches:
      - all_jobs_can_compare_against_prev_runs_clean_trigger

jobs:
  run_scheduled_amd_ci:
    name: Trigger Scheduled AMD CI
    runs-on: ubuntu-22.04
    if: ${{ always() }}
    steps:
      - name: Trigger scheduled AMD CI via workflow_run
        run: echo "Trigger scheduled AMD CI via workflow_run"
